### ISSUE TITLE
win客户端能用 mac客户端不能用 代码如下

### ISSUE THREAD

**Issue by Gongqiao24** [onplus/shadowsocks-heroku#43]
Last login: Fri Oct 13 16:14:49 on ttys000
/Software/VPN/Shadowsocks-Heroku/ss-h ; exit;
xiaojiaangdeMBP:~ Gongqiao24$ /Software/VPN/Shadowsocks-Heroku/ss-h ; exit;
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/Gongqiao24/config.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Number.<anonymous> (/Software/VPN/Shadowsocks-Heroku/ss-h:49:22)
    at Number.<anonymous> (/Software/VPN/Shadowsocks-Heroku/ss-h:326:4)
    at c (/Software/VPN/Shadowsocks-Heroku/ss-h:7221:3281)
    at Function.r.import (/Software/VPN/Shadowsocks-Heroku/ss-h:7221:3747)
    at /Software/VPN/Shadowsocks-Heroku/ss-h:7218:15
    at Object.<anonymous> (/Software/VPN/Shadowsocks-Heroku/ss-h:7221:1)
    at Module._compile (module.js:409:26)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

**Comment by liloli** [comment]
#31 
运行方式不是双击，而是要切换到程序所在目录，运行 `./ss-h`

**Comment by Gongqiao24** [comment]
@liloli 不是很懂。。。不是修改好config就启动ss-h么。。

**Comment by Gongqiao24** [comment]
@liloli 第六部文件-储存在那？。。没找到

**Comment by onplus** [comment]
no such file or directory, open '/Users/Gongqiao24/config.json'

治标方法 把这个文件夹/Users/Gongqiao24下面放一个config.json

**Comment by Gongqiao24** [comment]
@onplus 66666还是专业的牛逼，，一下子就搞好了

**Comment by chuhaibo** [comment]
Last login: Wed Oct 18 10:45:22 on ttys000
chuhaibotekiMacBook-Air:~ chuhaibo$ /Users/chuhaibo/Desktop/ss-h-mac/ss-h ; exit;
undefined:2
  "server": “sshforeric.herokuapp.com",
            ^

SyntaxError: Unexpected token “
    at Object.parse (native)
    at Number.<anonymous> (/Users/chuhaibo/Desktop/ss-h-mac/ss-h:51:17)
    at Number.<anonymous> (/Users/chuhaibo/Desktop/ss-h-mac/ss-h:326:4)
    at c (/Users/chuhaibo/Desktop/ss-h-mac/ss-h:7221:3281)
    at Function.r.import (/Users/chuhaibo/Desktop/ss-h-mac/ss-h:7221:3747)
    at /Users/chuhaibo/Desktop/ss-h-mac/ss-h:7218:15
    at Object.<anonymous> (/Users/chuhaibo/Desktop/ss-h-mac/ss-h:7221:1)
    at Module._compile (module.js:409:26)
    at _third_party_main.js:45:20
    at NativeModule.compile (node.js:1031:7)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

不能用，请问何解？

**Comment by chuhaibo** [comment]
Last login: Wed Oct 18 10:45:22 on ttys000
chuhaibotekiMacBook-Air:~ chuhaibo$ /Users/chuhaibo/Desktop/ss-h-mac/ss-h ; exit;
undefined:2
  "server": “***.herokuapp.com",
            ^

SyntaxError: Unexpected token “
    at Object.parse (native)
    at Number.<anonymous> (/Users/chuhaibo/Desktop/ss-h-mac/ss-h:51:17)
    at Number.<anonymous> (/Users/chuhaibo/Desktop/ss-h-mac/ss-h:326:4)
    at c (/Users/chuhaibo/Desktop/ss-h-mac/ss-h:7221:3281)
    at Function.r.import (/Users/chuhaibo/Desktop/ss-h-mac/ss-h:7221:3747)
    at /Users/chuhaibo/Desktop/ss-h-mac/ss-h:7218:15
    at Object.<anonymous> (/Users/chuhaibo/Desktop/ss-h-mac/ss-h:7221:1)
    at Module._compile (module.js:409:26)
    at _third_party_main.js:45:20
    at NativeModule.compile (node.js:1031:7)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

不能用，请问何解？

**Comment by onplus** [comment]
@chuhaibo  
校验一下json https://www.bejson.com/
https://github.com/onplus/shadowsocks-heroku/issues/1#issuecomment-334946631

**Comment by chuhaibo** [comment]
@onplus 已解决，可能是中文输入法的锅。从不需要更改内容的地方复制引号解决，感谢
