### ISSUE TITLE
安卓手机使用DoryNode 运行Node.js

### ISSUE THREAD

**Issue by onplus** [onplus/shadowsocks-heroku#7]
### 另一个局域网方案 https://github.com/onplus/shadowsocks-heroku/issues/47 

DoryNode下载地址：[Play](https://play.google.com/store/apps/details?id=io.tempage.dorynode)，[APKPure](https://apkpure.com/cn/dory-node-js-javascript/io.tempage.dorynode)

先下载解压 [shadowsocks-heroku/archive/re.zip](https://github.com/onplus/shadowsocks-heroku/archive/re.zip)，修改[config.json](https://github.com/onplus/shadowsocks-heroku/issues/1#issuecomment-334949649)内容

1. 在Dory中添加解压的文件夹
<img src='https://user-images.githubusercontent.com/31188782/31328966-5b57f87c-ad0a-11e7-91fd-a51185be5bd0.jpg' width=45%/>  <img src='https://user-images.githubusercontent.com/31188782/31328969-5b757050-ad0a-11e7-80d8-7c6d0ce0f78a.png' width=46%/>

2. 进入open，运行npm install 
  <img src='https://user-images.githubusercontent.com/31188782/31328967-5b63fec4-ad0a-11e7-9f1e-31701af07f00.jpg' width=50%/> 

3. 进入setting，填写loca.js，点击保存
  <img src='https://user-images.githubusercontent.com/31188782/31329017-a483d67e-ad0a-11e7-87d2-ed7095eb6079.png' width=50%/>

4.  点击start开始运行，默认代理socks5：127.0.0.1，端口1080

**Comment by onplus** [comment]
@tislam8888 这样会提供一个socks5的代理，还需要在其他软件上设置一下这个代理地址

**Comment by asen1987** [comment]
3.进入setting，填写loca.js，点击保存
应该是local.js

不过设置好后然后用ProxyDroid转全局，DoryNode那边日志里会立刻出现一大堆连接然后断开的日志然后卡死，翻查几遍后也没找到原因

**Comment by gogo81745** [comment]
@asen1987 

今天尝试用DoryNode+ProxyDroid，遇到同样的问题，及出现一大堆连接然后卡死断开
其实这个问题很好分析

ProxyDroid默认把全部网络连接都用DoryNode上代理，
然而DoryNode本身也需要网络连接，ProxyDroid把DoryNode的连接也用DoryNode代理，就成了一个无限循环。解决方法很简单，在ProxyDroid中设置让DoryNode的连接直连，其他程序通过DoryNode代理。

具体操作步骤：
在ProxyDroid中关闭GlobalProxy（全局代理，默认是开的）选项，
打开BypassMode（绕行模式）选项，
在 Individual Proxy（需要代理的软件）中勾选  d/node.js 这个软件
（这三个按钮是放在一起的，挺好找的）

绕行模式的意思是：除了勾选的软件，其他软件一律走代理
当然你也可以不勾选绕行模式，意思是：除了勾选的软件走代理，其他都不走代理
如果你只需要浏览器、GooglePlay等少数软件翻墙的翻墙的话，不打开绕行，直接勾要走代理的软件就行

**Comment by duiii** [comment]
手机没root，用不了ProxyDroid...有其他办法么

**Comment by scljy** [comment]
手机没root，用不了ProxyDroid...有其他办法么

**Comment by unstartdev** [comment]
@duiii postern

**Comment by Sloancc** [comment]
第二步报错：
2017-11-24 13:14:05 : pid 21549 started
module.js:471
    throw err;
    ^

Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/storage/emulated/0/shadowsocks-heroku-re/local.js:15:15)
    at Object.<anonymous> (/storage/emulated/0/shadowsocks-heroku-re/local.js:322:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
2017-11-24 13:14:05 : pid 21549 exited
with code : 1 / signal : 0

**Comment by spatgit** [comment]
@onplus @asen1987 请教二位。
使用 ProxyDroid+Termux 组合在 MI4c 手机上（安卓5.0，已 root）搭梯子，在 ProxyDroid 中指定“声破天” Spotify 和火狐 Firefox 走代理。
遇到的情况是：
Spotify 走代理正常；
Firefox 中 baidu.com（或其他国内网站）、amazon.com 走代理正常；google.com、Wikipedia.com、twitter.com、Facebook.com 无法走代理，页面长时无反应，同时 Termux 中 log 显示为（以访问 google.com 为例）>>
------
Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   pkg search <query>
Install a package: pkg install <package>
Upgrade packages:  pkg upgrade
Learn more:        pkg help
$ node /mnt/sdcard/Download/youguess/local.js
server listening at { address: '0.0.0.0', family: 'IPv4', port: 1090 }
local connected
concurrent connections: 1
connecting 52.89.179.237 via ws://youguess.herokuapp.com:80/
local connected
concurrent connections: 2
connecting 52.89.179.237 via ws://youguess.herokuapp.com:80/
local connected
concurrent connections: 3
connecting 216.58.197.100 via ws://youguess.herokuapp.com:80/
local connected
concurrent connections: 4
connecting 216.58.197.100 via ws://youguess.herokuapp.com:80/
local connected
concurrent connections: 5
local disconnected
concurrent connections: 4
local disconnected
concurrent connections: 3
remote disconnected
remote 216.58.197.100:443 Error: write after end
concurrent connections: 3
local connected
concurrent connections: 4
remote disconnected
connecting 216.58.197.115 via ws://sshjw0.herokuapp.com:80/
connecting 216.58.197.100 via ws://sshjw0.herokuapp.com:80/
local connected
concurrent connections: 5
concurrent connections: 6
connecting 74.125.204.138 via ws://sshjw0.herokuapp.com:80/
local connected
concurrent connections: 7
connecting 216.58.197.100 via ws://sshjw0.herokuapp.com:80/
remote disconnected
remote disconnected
remote disconnected
local disconnected
concurrent connections: 3
remote disconnected
remote 216.58.197.100:443 Error: write after end
concurrent connections: 3
local disconnected
concurrent connections: 2
remote disconnected
remote 74.125.204.138:443 Error: write after end
concurrent connections: 2
remote disconnected
remote 216.58.197.115:443 Error: read ECONNREFUSED
concurrent connections: 1
remote disconnected
remote 216.58.197.100:443 Error: read ECONNREFUSED
concurrent connections: 0
====

相应 config.json 的配置是：
------
{
  "server": "youguess.herokuapp.com",
  "local_address": "0.0.0.0",
  "scheme": "ws",
  "local_port": 1090,
  "remote_port": 80,
  "password": "idontguess",
  "timeout": 600,
  "method": "aes-256-cfb"
}
====

以上情况在 ProxyDroid+DoryNode 组合中也复现。

**Comment by wojiaoluyuan** [comment]
非root也能用，只要电脑能运行privoxy就行。
https://www.youtube.com/watch?v=Aro55ygbx58

**Comment by wojiaoluyuan** [comment]
有空有弄个视频。

**Comment by wojiaoluyuan** [comment]
有空我弄个视频，安卓手机如何录屏？
